# Generated by Django 5.2.8 on 2025-11-17 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor total esperado de la oportunidad', max_digits=12, verbose_name='Monto estimado')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('won', 'Ganada'), ('lost', 'Perdida')], default='open', max_length=10, verbose_name='Estado')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de cierre')),
                ('probability', models.PositiveSmallIntegerField(default=0, help_text='Probabilidad de ganar la oportunidad (0-100%)', verbose_name='Probabilidad de cierre (%)')),
                ('source', models.CharField(blank=True, help_text='Ej: Referido, Web, Llamada, Evento, etc.', max_length=100, verbose_name='Origen')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='customers.customer', verbose_name='Cliente')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor responsable')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-created_at'],
            },
        ),
    ]
