# Generated by Django 5.2.8 on 2025-11-19 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_assigned_to'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='priority',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto estimado'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('calificada', 'Calificada'), ('propuesta', 'Propuesta enviada'), ('negociacion', 'En negociación'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='abierta', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['assigned_to', 'status'], name='opportuniti_assigne_f88dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='opportuniti_expecte_c56295_idx'),
        ),
    ]
