# Generated by Django 5.2.8 on 2025-11-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente de Ventas'), ('vendedor', 'Vendedor')], default='vendedor', max_length=20),
        ),
    ]
