# Generated by Django 5.2.6 on 2025-11-19 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('llamada', 'Llamada'), ('email', 'Email'), ('reunion', 'Reunión'), ('nota', 'Nota')], default='nota', max_length=20, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('notes', models.TextField(verbose_name='Notas')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-date'],
            },
        ),
    ]
