# Generated by Django 5.2.8 on 2025-11-20 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('followups', '0001_initial'),
        ('opportunities', '0003_opportunity_updated_at_alter_opportunity_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='related_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='related_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='opportunities.opportunity'),
        ),
    ]
