# Generated by Django 5.2.8 on 2025-11-19 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_assigned_to'),
        ('followups', '0002_initial'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='is_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Recordatorio enviado'),
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='followup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['user', 'status'], name='followups_f_user_id_654797_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['date'], name='followups_f_date_034f06_idx'),
        ),
    ]
