# Generated by Django 5.2.8 on 2025-11-20 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('report_type', models.CharField(choices=[('sales', 'Reporte de Ventas'), ('customers', 'Reporte de Clientes'), ('sellers', 'Reporte de Vendedores'), ('followups', 'Reporte de Seguimientos'), ('opportunities', 'Reporte de Oportunidades'), ('pipeline', 'Análisis de Pipeline')], max_length=20, verbose_name='Tipo de Reporte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('data', models.JSONField(verbose_name='Datos del Reporte')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte Guardado',
                'verbose_name_plural': 'Reportes Guardados',
                'ordering': ['-created_at'],
            },
        ),
    ]
